# Generated by Django 2.2 on 2020-09-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200910_2136'),
        ('mainapp', '0002_auto_20200913_1708'),
    ]

    operations = [
    ]
